// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import * as Plugin_1 from '@@/core/helmet.ts';
import { PluginManager } from 'umi';
import * as Plugin_2 from '/home/hit802/RAG1/ragflow/web/src/.umi/plugin-clickToComponent/runtime.tsx';
import * as Plugin_0 from '/home/hit802/RAG1/ragflow/web/src/app.tsx';

function __defaultExport(obj) {
  if (obj.default) {
    return typeof obj.default === 'function' ? obj.default() : obj.default;
  }
  return obj;
}
export function getPlugins() {
  return [
    {
      apply: __defaultExport(Plugin_0),
      path:
        process.env.NODE_ENV === 'production'
          ? void 0
          : '/home/hit802/RAG1/ragflow/web/src/app.tsx',
    },
    {
      apply: Plugin_1,
      path:
        process.env.NODE_ENV === 'production' ? void 0 : '@@/core/helmet.ts',
    },
    {
      apply: Plugin_2,
      path:
        process.env.NODE_ENV === 'production'
          ? void 0
          : '/home/hit802/RAG1/ragflow/web/src/.umi/plugin-clickToComponent/runtime.tsx',
    },
  ];
}

export function getValidKeys() {
  return [
    'patchRoutes',
    'patchClientRoutes',
    'modifyContextOpts',
    'modifyClientRenderOpts',
    'rootContainer',
    'innerProvider',
    'i18nProvider',
    'accessProvider',
    'dataflowProvider',
    'outerProvider',
    'render',
    'onRouteChange',
  ];
}

let pluginManager = null;

export function createPluginManager() {
  pluginManager = PluginManager.create({
    plugins: getPlugins(),
    validKeys: getValidKeys(),
  });

  return pluginManager;
}

export function getPluginManager() {
  return pluginManager;
}
