// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {
    '1': { path: '/login', layout: false, id: '1' },
    '2': { path: '/login-next', layout: false, id: '2' },
    '3': { path: '/next-chats/share', layout: false, id: '3' },
    '4': { path: '/agent/share', layout: false, id: '4' },
    '5': { path: '/next-chats/widget', layout: false, id: '5' },
    '6': { path: '/agent-list', parentId: '@@/global-layout', id: '6' },
    '7': { path: '/document/:id', layout: false, id: '7' },
    '8': { path: '/*', layout: false, id: '8' },
    '9': { path: '', layout: false, parentId: '10', id: '9', originPath: '/' },
    '10': { path: '/', isWrapper: true, layout: false, id: '10' },
    '11': { path: '/', parentId: '9', id: '11' },
    '12': { path: '/datasets', layout: false, id: '12' },
    '13': { path: '/datasets', parentId: '12', id: '13' },
    '14': { path: '/next-chats', layout: false, id: '14' },
    '15': { path: '/next-chats', parentId: '14', id: '15' },
    '16': { path: '/next-chat/:id', layout: false, id: '16' },
    '17': { path: '/next-searches', layout: false, id: '17' },
    '18': { path: '/next-searches', parentId: '17', id: '18' },
    '19': { path: '/memories', layout: false, id: '19' },
    '20': { path: '/memories', parentId: '19', id: '20' },
    '21': { path: '/memory', layout: false, id: '21' },
    '22': { path: '/memory', layout: false, parentId: '21', id: '22' },
    '23': { path: '/memory//memory-message/:id', parentId: '22', id: '23' },
    '24': { path: '/memory//memory-setting/:id', parentId: '22', id: '24' },
    '25': { path: '/next-search/:id', layout: false, id: '25' },
    '26': { path: '/next-search/share', layout: false, id: '26' },
    '27': { path: '/agents', layout: false, id: '27' },
    '28': { path: '/agents', parentId: '27', id: '28' },
    '29': { path: '/agent-log-page/:id', layout: false, id: '29' },
    '30': { path: '/agent/:id', layout: false, id: '30' },
    '31': { path: '/agent-templates', layout: false, id: '31' },
    '32': { path: '/files', layout: false, id: '32' },
    '33': { path: '/files', parentId: '32', id: '33' },
    '34': { path: '/dataset', layout: false, id: '34' },
    '35': {
      path: '/dataset',
      redirect: '/dataset/dataset',
      parentId: '34',
      id: '35',
    },
    '36': { path: '/dataset', layout: false, id: '36' },
    '37': { path: '/dataset/dataset/:id', parentId: '36', id: '37' },
    '38': { path: '/dataset/testing/:id', parentId: '36', id: '38' },
    '39': { path: '/dataset/knowledge-graph/:id', parentId: '36', id: '39' },
    '40': { path: '/dataset/dataset-overview/:id', parentId: '36', id: '40' },
    '41': { path: '/dataset/dataset-setting/:id', parentId: '36', id: '41' },
    '42': { path: '/dataflow-result', layout: false, id: '42' },
    '43': { path: '/chunk/parsed/chunks', layout: false, id: '43' },
    '44': { path: '/chunk', layout: false, id: '44' },
    '45': { path: '/chunk', parentId: '44', id: '45' },
    '46': { path: '/chunk/chunk/:id', parentId: '45', id: '46' },
    '47': { path: '/chunk/result/:id', parentId: '45', id: '47' },
    '48': { path: '/chunk', layout: false, id: '48' },
    '49': { path: '/user-setting', layout: false, id: '49' },
    '50': {
      path: '/user-setting',
      redirect: '/user-setting/data-source',
      parentId: '49',
      id: '50',
    },
    '51': { path: '/user-setting/profile', parentId: '49', id: '51' },
    '52': { path: '/user-setting/locale', parentId: '49', id: '52' },
    '53': { path: '/user-setting/model', parentId: '49', id: '53' },
    '54': { path: '/user-setting/team', parentId: '49', id: '54' },
    '55': { path: '/user-setting/api', parentId: '49', id: '55' },
    '56': { path: '/user-setting/mcp', parentId: '49', id: '56' },
    '57': { path: '/user-setting/data-source', parentId: '49', id: '57' },
    '58': {
      path: '/user-setting/data-source/data-source-detail-page',
      layout: false,
      id: '58',
    },
    '59': { path: '/admin', layout: false, id: '59' },
    '60': { path: '', parentId: '59', id: '60' },
    '61': {
      path: '',
      parentId: '62',
      id: '61',
      originPath: '/admin/users/:id',
    },
    '62': {
      path: '/admin/users/:id',
      isWrapper: true,
      parentId: '59',
      id: '62',
    },
    '63': { path: '', parentId: '64', id: '63', originPath: '/admin' },
    '64': { path: '/admin', isWrapper: true, parentId: '59', id: '64' },
    '65': { path: '/admin/services', parentId: '63', id: '65' },
    '66': { path: '/admin/users', parentId: '63', id: '66' },
    '@@/global-layout': { id: '@@/global-layout', path: '/', isLayout: true },
  } as const;
  return {
    routes,
    routeComponents: {
      '1': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__login-next__index" */ '@/pages/login-next/index.tsx'
          ),
      ),
      '2': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__login-next__index" */ '@/pages/login-next/index.tsx'
          ),
      ),
      '3': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__next-chats__share__index" */ '@/pages/next-chats/share/index.tsx'
          ),
      ),
      '4': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__agent__share__index" */ '@/pages/agent/share/index.tsx'
          ),
      ),
      '5': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__next-chats__widget__index" */ '@/pages/next-chats/widget/index.tsx'
          ),
      ),
      '6': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__agents__index" */ '@/pages/agents/index.tsx'
          ),
      ),
      '7': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__document-viewer__index" */ '@/pages/document-viewer/index.tsx'
          ),
      ),
      '8': React.lazy(
        () => import(/* webpackChunkName: "p__404" */ '@/pages/404.jsx'),
      ),
      '9': React.lazy(
        () =>
          import(/* webpackChunkName: "layouts__next" */ '@/layouts/next.tsx'),
      ),
      '10': React.lazy(
        () =>
          import(
            /* webpackChunkName: "wrappers__auth" */ '@/wrappers/auth.tsx'
          ),
      ),
      '11': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__home__index" */ '@/pages/home/index.tsx'
          ),
      ),
      '12': React.lazy(
        () =>
          import(/* webpackChunkName: "layouts__next" */ '@/layouts/next.tsx'),
      ),
      '13': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__datasets__index" */ '@/pages/datasets/index.tsx'
          ),
      ),
      '14': React.lazy(
        () =>
          import(/* webpackChunkName: "layouts__next" */ '@/layouts/next.tsx'),
      ),
      '15': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__next-chats__index" */ '@/pages/next-chats/index.tsx'
          ),
      ),
      '16': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__next-chats__chat__index" */ '@/pages/next-chats/chat/index.tsx'
          ),
      ),
      '17': React.lazy(
        () =>
          import(/* webpackChunkName: "layouts__next" */ '@/layouts/next.tsx'),
      ),
      '18': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__next-searches__index" */ '@/pages/next-searches/index.tsx'
          ),
      ),
      '19': React.lazy(
        () =>
          import(/* webpackChunkName: "layouts__next" */ '@/layouts/next.tsx'),
      ),
      '20': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__memories__index" */ '@/pages/memories/index.tsx'
          ),
      ),
      '21': React.lazy(
        () =>
          import(/* webpackChunkName: "layouts__next" */ '@/layouts/next.tsx'),
      ),
      '22': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__memory__index" */ '@/pages/memory/index.tsx'
          ),
      ),
      '23': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__memory__memory-message__index" */ '@/pages/memory/memory-message/index.tsx'
          ),
      ),
      '24': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__memory__memory-setting__index" */ '@/pages/memory/memory-setting/index.tsx'
          ),
      ),
      '25': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__next-search__index" */ '@/pages/next-search/index.tsx'
          ),
      ),
      '26': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__next-search__share__index" */ '@/pages/next-search/share/index.tsx'
          ),
      ),
      '27': React.lazy(
        () =>
          import(/* webpackChunkName: "layouts__next" */ '@/layouts/next.tsx'),
      ),
      '28': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__agents__index" */ '@/pages/agents/index.tsx'
          ),
      ),
      '29': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__agents__agent-log-page" */ '@/pages/agents/agent-log-page.tsx'
          ),
      ),
      '30': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__agent__index" */ '@/pages/agent/index.tsx'
          ),
      ),
      '31': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__agents__agent-templates" */ '@/pages/agents/agent-templates.tsx'
          ),
      ),
      '32': React.lazy(
        () =>
          import(/* webpackChunkName: "layouts__next" */ '@/layouts/next.tsx'),
      ),
      '33': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__files__index" */ '@/pages/files/index.tsx'
          ),
      ),
      '34': React.lazy(
        () =>
          import(/* webpackChunkName: "layouts__next" */ '@/layouts/next.tsx'),
      ),
      '35': React.lazy(() => import('./EmptyRoute')),
      '36': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__dataset__index" */ '@/pages/dataset/index.tsx'
          ),
      ),
      '37': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__dataset__dataset__index" */ '@/pages/dataset/dataset/index.tsx'
          ),
      ),
      '38': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__dataset__testing__index" */ '@/pages/dataset/testing/index.tsx'
          ),
      ),
      '39': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__dataset__knowledge-graph__index" */ '@/pages/dataset/knowledge-graph/index.tsx'
          ),
      ),
      '40': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__dataset__dataset-overview__index" */ '@/pages/dataset/dataset-overview/index.tsx'
          ),
      ),
      '41': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__dataset__dataset-setting__index" */ '@/pages/dataset/dataset-setting/index.tsx'
          ),
      ),
      '42': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__dataflow-result__index" */ '@/pages/dataflow-result/index.tsx'
          ),
      ),
      '43': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__chunk__parsed-result__add-knowledge__components__knowledge-chunk__index" */ '@/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/index.tsx'
          ),
      ),
      '44': React.lazy(() => import('./EmptyRoute')),
      '45': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__chunk__index" */ '@/pages/chunk/index.tsx'
          ),
      ),
      '46': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__chunk__chunk-result__index" */ '@/pages/chunk/chunk-result/index.tsx'
          ),
      ),
      '47': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__chunk__result-view__index" */ '@/pages/chunk/result-view/index.tsx'
          ),
      ),
      '48': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__chunk__index" */ '@/pages/chunk/index.tsx'
          ),
      ),
      '49': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__user-setting__index" */ '@/pages/user-setting/index.tsx'
          ),
      ),
      '50': React.lazy(() => import('./EmptyRoute')),
      '51': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__user-setting__profile__index" */ '@/pages/user-setting/profile/index.tsx'
          ),
      ),
      '52': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__user-setting__setting-locale__index" */ '@/pages/user-setting/setting-locale/index.tsx'
          ),
      ),
      '53': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__user-setting__setting-model__index" */ '@/pages/user-setting/setting-model/index.tsx'
          ),
      ),
      '54': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__user-setting__setting-team__index" */ '@/pages/user-setting/setting-team/index.tsx'
          ),
      ),
      '55': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__user-setting__setting-api__index" */ '@/pages/user-setting/setting-api/index.tsx'
          ),
      ),
      '56': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__user-setting__mcp__index" */ '@/pages/user-setting/mcp/index.tsx'
          ),
      ),
      '57': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__user-setting__data-source__index" */ '@/pages/user-setting/data-source/index.tsx'
          ),
      ),
      '58': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__user-setting__data-source__data-source-detail-page__index" */ '@/pages/user-setting/data-source/data-source-detail-page/index.tsx'
          ),
      ),
      '59': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__admin__layouts__root-layout" */ '@/pages/admin/layouts/root-layout.tsx'
          ),
      ),
      '60': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__admin__login" */ '@/pages/admin/login.tsx'
          ),
      ),
      '61': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__admin__user-detail" */ '@/pages/admin/user-detail.tsx'
          ),
      ),
      '62': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__admin__wrappers__authorized" */ '@/pages/admin/wrappers/authorized.tsx'
          ),
      ),
      '63': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__admin__layouts__navigation-layout" */ '@/pages/admin/layouts/navigation-layout.tsx'
          ),
      ),
      '64': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__admin__wrappers__authorized" */ '@/pages/admin/wrappers/authorized.tsx'
          ),
      ),
      '65': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__admin__service-status" */ '@/pages/admin/service-status.tsx'
          ),
      ),
      '66': React.lazy(
        () =>
          import(
            /* webpackChunkName: "p__admin__users" */ '@/pages/admin/users.tsx'
          ),
      ),
      '@@/global-layout': React.lazy(
        () =>
          import(
            /* webpackChunkName: "layouts__index" */ '/home/hit802/RAG1/ragflow/web/src/layouts/index.tsx'
          ),
      ),
    },
  };
}
